# Generated by Django 2.2 on 2019-04-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('finance_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('productionLevel', models.PositiveIntegerField()),
                ('salesPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unitCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('totalProductionCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('grossMargin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fixedCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captrade.Company')),
            ],
        ),
    ]
